site_name: CA про ПЛК
site_url: https://manual.saplc.ru/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Montserrat
  features:
    - glightbox
    - navigation.instant
    - navigation.tabs
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
  
  logo: img/logo.svg
  favicon: img/favicon.svg
  icon:
    annotation: material/chevron-right-circle
 
  
  language: ru
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: Red
      accent: grey

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: Red
      accent: grey 
      
extra_css:
  - stylesheets/extra.css
extra:
  generator: false


extra_javascript:
  - overrides/main.js
  - path: https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js
    type: module


nav:
  - Главная: index.md 
  - Руководство пользователя:  
    
    - Основные модули:
      - Модуль основной IPCSA-OG-GM: user_manual/GM.md
    - Дискретные модули:
      - Модуль дискретного ввода IPCSA-OG-DI: user_manual/DI.md
      - Модуль дискретного вывода IPCSA-OG-DO: user_manual/DO.md
      - Модуль дискретного вывода ШИМ IPCSA-OG-DPWM: user_manual/DPWM.md
    - Аналоговые модули:
      - Модуль аналогового ввода тока IPCSA-OG-AIC: user_manual/AIC.md
      - Модуль аналогового ввода напряжения IPCSA-OG-AIV: user_manual/AIV.md 
      - Модуль аналогового ввода термопары IPCSA-OG-AITC: user_manual/AITC.md
      - Модуль аналогового ввода термосопротивления IPCSA-OG-AITR: user_manual/AITR.md
      - Модуль аналогового ввода синусно-косинусного трансформатора IPCSA-OG-AISCT: user_manual/AISCT.md
      - Модуль аналогового ввода виброскорости IPCSA-OG-AIVS: user_manual/AIVS.md
      - Модуль аналогового вывода IPCSA-OG-AO: user_manual/AO.md
    - Интерфейсные модули:
       - Модуль интерфейсный RS-485/422 IPCSA-OG-IF485/422: user_manual/IF485_422.md
       - Модуль интерфейсный IFARINC IPCSA-OG-IFARINC: user_manual/IFARINC.md
       - Модуль интерфейсный IFCAN IPCSA-OG-IFCAN: user_manual/IFCAN.md
       - Модуль интерфейсный IF232 IPCSA-OG-IF232: user_manual/IF232.md
       - Модуль интерфейсный IFHART IPCSA-OG-IFHART: user_manual/IFHART.md
    - Специальные модули:
      - Модуль счета импульсов IPCSA-OG-SPPC: user_manual/SPPC.md
      - Модуль ввода питания IPCSA-OG-SPPM: user_manual/SPPM.md
      - Модуль оконечный IPCSA-OG-SPТM: user_manual/SPTM.md
      - Модуль управления драйвером шагового двигателя IPCSA-OG-SSMD: user_manual/SSMD.md
      - Модуль расширения коммутации IPCSA-OG-SPSE: user_manual/SPSE.md
    - Основные сведения: user_manual/basic_nformation.md
    - Составление групп: user_manual/groups.md
    - Составление сборки: user_manual/assembly.md
    - Монтаж и демонтаж модулей: user_manual/installation.md 
    - Техническое обслуживание: user_manual/maintenance.md 
  
  - Статьи: blog/index.md
  - Форум: https://t.me/+jT-lYOb1kB04MmQ6


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr

plugins:
 - search
 - blog:
     authors_file: .authors.yml
 - tags:
      tags_file: tags.md
 


 