site_name: CA про ПЛК
site_url: https://manual.saplc.ru/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Montserrat
  features:
    - glightbox
    - navigation.instant
    - navigation.tabs
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
  
  logo: img/logo.svg
  favicon: img/favicon.svg
  icon:
    annotation: material/chevron-right-circle
 
  
  language: ru
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: Red
      accent: grey

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: Red
      accent: grey 
      
extra_css:
  - stylesheets/extra.css
extra:
  generator: false


extra_javascript:
  - overrides/main.js
  - path: https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js
    type: module
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Главная: index.md 
  - Руководство пользователя:  
    
    - Основные модули:
      - Модуль основной PP-P5-GM: user_manual/GM.md
    - Дискретные модули:
      - Модуль дискретного ввода PP-P5-DI: user_manual/DI.md
      - Модуль дискретного вывода PP-P5-DO: user_manual/DO.md
      - Модуль дискретного вывода ШИМ PP-P5-DPWM: user_manual/DPWM.md
    - Аналоговые модули:
      - Модуль аналогового ввода тока PP-P5-AIC: user_manual/AIC.md
      - Модуль аналогового ввода напряжения PP-P5-AIV: user_manual/AIV.md 
      - Модуль аналогового ввода термопары PP-P5-AITC: user_manual/AITC.md
      - Модуль аналогового ввода термосопротивления PP-P5-AITR: user_manual/AITR.md
      - Модуль аналогового ввода синусно-косинусного трансформатора PP-P5-AISCT: user_manual/AISCT.md
      - Модуль аналогового ввода виброскорости PP-P5-AIVS: user_manual/AIVS.md
      - Модуль аналогового вывода PP-P5-AO: user_manual/AO.md
    - Интерфейсные модули:
       - Модуль интерфейсный RS-485/422 PP-P5-IF485/422: user_manual/IF485_422.md
       - Модуль интерфейсный IFARINC PP-P5-IFARINC: user_manual/IFARINC.md
       - Модуль интерфейсный IFCAN PP-P5-IFCAN: user_manual/IFCAN.md
       - Модуль интерфейсный IF232 PP-P5-IF232: user_manual/IF232.md
       - Модуль интерфейсный IFHART PP-P5-IFHART: user_manual/IFHART.md
    - Специальные модули:
      - Модуль счета импульсов PP-P5-SPPC: user_manual/SPPC.md
      - Модуль ввода питания PP-P5-SPPM: user_manual/SPPM.md
      - Модуль оконечный PP-P5-SPТM: user_manual/SPTM.md
      - Модуль управления драйвером шагового двигателя PP-P5-SSMD: user_manual/SSMD.md
      - Модуль расширения коммутации PP-P5-SPSE: user_manual/SPSE.md
    - Основные сведения: user_manual/basic_nformation.md
    - Составление групп: user_manual/groups.md
    - Составление сборки: user_manual/assembly.md
    - Монтаж и демонтаж модулей: user_manual/installation.md 
    - Техническое обслуживание: user_manual/maintenance.md 
  
  - Статьи: blog/index.md
  - Форум: https://t.me/+jT-lYOb1kB04MmQ6


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - pymdownx.arithmatex:
     generic: true

plugins:
 - search
 - blog:
     authors_file: .authors.yml
 - tags:
      tags_file: tags.md
 


 